[package]
name = "todo_api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
axum = "0.8.4"
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = "1.0"
thiserror = "2.0.16"
tokio = {version ="1.45.1", features =["full"]}
